version: '3.8'

services:
  postgres_task_manager_ft:
    container_name: task_manager_ft_postgres_container
    image: postgres:14.11
    environment:
      POSTGRES_DB: ${TASK_MANAGER_FT_RDS_DB_NAME:-task_manager_ft}
      POSTGRES_USER: ${TASK_MANAGER_FT_RDS_USERNAME:-task_manager_ft}
      POSTGRES_PASSWORD: ${TASK_MANAGER_FT_RDS_PASSWORD:-testpwd1}
      PGDATA: /data/postgres_task_manager_ft
    volumes:
      - postgres_task_manager_ft:/data/postgres_task_manager_ft
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_task_manager_ft:
